top/store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('product/<int:pk>', views.product, name='product'),
    path('guest_register/<int:pk>', views.guest_register, name='guest_register'),
    path('cart/', views.cart, name='cart'),
    path('create_order/', views.create_order, name='create_order'),
    path('favorite/', views.favorite_page, name='favorite'),
    path('orders/', views.orders, name='orders')
]

top/top/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include(('store.urls', 'store'), namespace='store')),
    path('users/', include(('users.urls', 'users'), namespace='users'))
]  
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

top/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_out/', views.sign_out, name='sign_out'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('reset_password/', views.reset_password, name='reset_password')
]

top/store/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        db_table = 'categories'

    def __str__(self):
        return self.name


class Brand(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        db_table = 'brands'

    def __str__(self):

        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    price = models.IntegerField()
    is_new = models.BooleanField()
    is_discounted = models.BooleanField()
    category = models.ForeignKey('store.Category', on_delete=models.CASCADE)
    brand = models.ForeignKey('store.Brand', on_delete=models.CASCADE)
    image = models.ImageField(default='default.png')
    favorite = models.ManyToManyField(User, related_name='favorite_products')

    def __str__(self):
        return self.name


class SliderImage(models.Model):
    image = models.ImageField()

    def __str__(self):
        return f"Image #{self.pk}"


class CartItem(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    guest = models.ForeignKey(
        'store.Guest', on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    chosen = models.BooleanField(default=False)

    def __str__(self):
        return self.product.name

    def total_price(self):
        return self.product.price * self.quantity


class Guest(models.Model):
    token = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = 'guests'


class Order(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    total_price = models.IntegerField()

    def __str__(self):
        return f"Заказ №{self.pk}"

    def order_products_list(self):
        return ', '.join(
            [f'{order.product.name} {order.amount} шт'
             for order in self.order_products.all()]
        )


class OrderProduct(models.Model):
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, related_name='order_products')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.IntegerField()
    total = models.IntegerField()

    def __str__(self):
        return self.product.name


RATE_CHOICES = [
    (5, 'Отлично'),
    (4, 'Хорошо'),
    (3, 'Нормально'),
    (2, 'Плохо'),
    (1, 'Ужасно'),
]

class Review(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    text = models.TextField(blank=True)
    rating = models.PositiveSmallIntegerField(choices=RATE_CHOICES)

    def __str__(self):
        return f'{self.customer.username} о {self.product.name}'

top/store/forms.py
from django import forms
from .bulma_mixin import BulmaMixin
from .models import *


class OrderForm(BulmaMixin, forms.ModelForm):
    address = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Напишите адрес доставки'
    }))
    phone = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Напишите номер телефона'
    }))

    class Meta:
        model = Order
        fields = ['address', 'phone']


class RateForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea(
        attrs={'class': 'textarea'}
    ), label='Можете оставить ваш отзыв здесь')
    rating = forms.ChoiceField(choices=RATE_CHOICES, required=True,
                               label='Оцените продукт')

    class Meta:
        model = Review
        fields = ['text', 'rating']

top/store/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import OrderForm, RateForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator


def home(request):
    products = Product.objects.all()
    slides = SliderImage.objects.all()
    category = request.GET.get('category')
    brand = request.GET.get('brand')

    action = request.GET.get('action')
    if action:
        favorite(request)
        return redirect('store:home')

    products = products.filter(category=category) \
        if category else products
    products = products.filter(brand=brand) \
        if brand else products

    amount = show_amount(request)

    pages = Paginator(products, 6)
    page = request.GET.get('page')
    products = pages.get_page(page)
    products_pages = products.paginator.get_elided_page_range(products.number, on_each_side=2, on_ends=1)

    return render(request, 'home.html',
                  {'products': products,
                   'slides': slides,
                   'amount': amount,
                   'products_pages':products_pages})


def product(request, pk):
    product_data = Product.objects.get(pk=pk)
    action = request.GET.get('action')

    # система отзыва
    form = RateForm(request.POST or None)

    if form.is_valid():
        instance = form.save(commit=False)
        instance.customer = request.user
        instance.product = product_data
        instance.save()
        return redirect('store:product', pk=product_data.pk)

    if action:
        favorite(request, pk)
        return redirect('store:product', pk=pk)

    amount = show_amount(request)
    return render(request, 'product.html',
                  {'product': product_data, 'form': form, 'amount': amount})


def guest_register(request, pk):
    token = request.COOKIES['csrftoken']
    guest = Guest.objects.filter(token=token)

    if not guest:
        Guest.objects.create(token=token)
        guest = Guest.objects.filter(token=token)

    cart_item = CartItem.objects.filter(
        product=pk,
        guest=guest[0] if request.user.is_anonymous else None,
        customer=request.user if request.user.is_authenticated else None
    )

    if not cart_item:
        CartItem.objects.create(
            guest=guest[0] if request.user.is_anonymous else None,
            product=Product.objects.get(pk=pk),
            quantity=1,
            customer=request.user if request.user.is_authenticated else None
        )

    else:
        cart_item[0].quantity += 1
        cart_item[0].save()

    pk = request.GET.get('pk')
    return redirect('store:home') \
        if not pk else redirect('store:product', pk=pk)


def cart(request):
    token = request.COOKIES['csrftoken']
    guest = Guest.objects.filter(token=token)

    action = request.GET.get('action')
    cart_item_pk = request.GET.get('pk')
    confirm_delete = False

    if action == 'delete':
        confirm_delete = True
    elif action == 'increment' or action == 'decrement':
        edit_cart(action, cart_item_pk)
        return redirect('store:cart')
    elif action == 'favorite':
        favorite(request)
        return redirect('store:cart')
    elif action == 'add_chosen':
        CartItem.objects.filter(pk=cart_item_pk).update(chosen=True)
    elif action == 'remove_chosen':
        CartItem.objects.filter(pk=cart_item_pk).update(chosen=False)

    if request.GET.get('confirm'):
        CartItem.objects.get(pk=cart_item_pk).delete()
        return redirect('store:cart')

    if request.user.is_authenticated:
        cart_items = CartItem.objects.filter(customer=request.user)
    else:
        cart_items = CartItem.objects.filter(guest=guest[0]) if guest else []

    chosen_items = cart_items.filter(chosen=True)
    total_quantity = sum([i.quantity for i in chosen_items])
    total_sum = sum([i.total_price() for i in chosen_items])

    return render(request,
                  'cart.html',
                  {'cart_items': cart_items,
                   'confirm_delete': confirm_delete,
                   'total_quantity': total_quantity,
                   'total_sum': total_sum,
                   'chosen_items': chosen_items
                   })


def edit_cart(action, pk):
    cart_item = CartItem.objects.get(pk=pk)
    if action == 'increment':
        cart_item.quantity += 1
        cart_item.save()

    if action == 'decrement' and cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()


@login_required(login_url='/users/sign_in/')
def create_order(request):
    cart_items = CartItem.objects.filter(customer=request.user, chosen=True)
    if not cart_items:
        return render(request, 'error.html', {})

    total_price = sum(item.total_price() for item in cart_items)
    amount = sum(item.quantity for item in cart_items)

    form = OrderForm(request.POST or None)

    if form.is_valid():
        order = Order.objects.create(
            address=request.POST.get('address'),
            phone=request.POST.get('phone'),
            total_price=total_price,
            customer=request.user
        )
        for item in cart_items:
            OrderProduct.objects.create(
                order=order,
                product=item.product,
                amount=item.quantity,
                total=item.total_price()
            )
        cart_items.delete()
        return redirect('store:home')
    return render(request, 'order_create.html',
                  {'cart_items': cart_items,
                   'total_price': total_price,
                   'amount': amount,
                   'form': form
                   })


def favorite(request, pk=None):
    product_pk = request.GET.get('product') if not pk else pk

    product_detail = Product.objects.get(pk=product_pk)
    product_detail.favorite.add(request.user) \
        if request.user not in product_detail.favorite.all() \
        else product_detail.favorite.remove(request.user)


def favorite_page(request):
    favorite_products = Product.objects.filter(favorite=request.user)
    action = request.GET.get('action')
    if action:
        favorite(request)
        return redirect('store:favorite')

    amount = show_amount(request)
    return render(request, 'favorite.html',
                  {'favorites': favorite_products, 'amount': amount})


def orders(request):
    orders_list = Order.objects.filter(customer=request.user)
    amount = show_amount(request)
    return render(request, 'orders.html', {'orders': orders_list, 'amount': amount})


def show_amount(request):
    token = request.COOKIES.get('csrftoken')
    guest = Guest.objects.filter(token=token).last()
    print(guest)

    cart_items = CartItem.objects.filter(
        customer=request.user
        if request.user.is_authenticated else None,
        guest=guest if request.user.is_anonymous else None
    )

    return sum([i.quantity for i in cart_items])

top/store/templates/base_layout.html
{% load static from static %}
{% load category %}
{% load brand %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'static/bulma.css' %}">
    <link rel="stylesheet" href="{% static 'static/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-carousel@4.0.3/dist/css/bulma-carousel.min.css">
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

</head>

<body>
  <div class="container" style="background-color: lightgreen; max-width: 100%; height: 100%;">
    <nav class="navbar is-primary" role="navigation" aria-label="main navigation">
        <div class="navbar-brand has-text-weight-bold has-text-white">
          <a class="navbar-item" href="{% url 'store:home' %}">
            <ion-icon name="flower-outline"></ion-icon>
              YOUR GARDEN
            <ion-icon name="flower-outline"></ion-icon>
          </a>
        </div>
        <div class="navbar-menu">
            <div class="navbar-start" title="на главную">
                <a href="{% url 'store:home' %}" class="navbar-item">
                    <ion-icon name="home-outline"></ion-icon>
                </a>
                <div class="navbar-item has-dropdown is-hoverable">
                  <a class="navbar-link">
                    Каталог
                  </a>
                  <div class="navbar-dropdown">
                    <a class="navbar-item">
                      {% categories %}
                    </a>
                  </div>
    
                </div>
            </div>
            {% csrf_token %}
            
            <div class="navbar-end">
                <div class="container">
                    <form method="get" action="/store/home/">
                      <div class="field has-addons mt-4">
                        <div class="control">
                          <input class="input" type="search" name="search">
                        </div>
                        <div class="control">
                          <button class="button" type="submit"><ion-icon name="search"></ion-icon>
                        </div>
                      </div>
                    </form>
                </div>

                {% if user.is_authenticated %}
                <a class="navbar-item has-text-white is-size-3" href="{% url 'store:cart' %}">
                    <ion-icon name="cart-outline"></ion-icon>
                </a>
                <div class="navbar-item has-dropdown is-hoverable">
                    <div class="navbar-link">
                        {{ user }}
                    </div>
                    <div class="navbar-dropdown">
                        <a class="navbar-item has-text-danger" href="{% url 'users:edit_profile' %}">
                              Редактировать <br>
                              профиль
                        </a>
                        <a class="navbar-item has-text-danger" href="{% url 'users:reset_password' %}">
                              Изменить пароль
                        </a>
                        <a class="navbar-item has-text-danger" href="{% url 'store:favorite' %}">
                              Избранное
                        </a>
                         <a class="navbar-item has-text-danger" href="{% url 'store:orders' %}">
                              Мои заказы
                        </a>
                        <a class="navbar-item has-text-danger" href="{% url 'users:sign_out' %}">
                              Выйти
                        </a>
                    </div>
                </div>
                {% else %}
                <a class="navbar-item" href="{% url 'users:sign_in' %}">
                    <button class="button">Войти</button>
                </a>
                {% endif %}
            </div>
        </div>
    </nav>

    {% block auth %}
    {% endblock %}

    {% block slider %}
    {% endblock %}

    {% block content %}
    {% endblock %}
    
   

    <script src="https://cdn.jsdelivr.net/npm/bulma-carousel@4.0.3/dist/js/bulma-carousel.min.js"></script>
    <script>
        bulmaCarousel.attach('#carousel-demo', {
            slidesToScroll: 1,
            slidesToShow: 1,
            autoplay: true,
            autoplaySpeed: 1000,
        })
    </script>
  </div>

</div>
</body>


</html>

top/store/templates/brands.html
<div class="menu-label">
    <div class="title is-size-6">
        Производители
    </div>
</div>
{% for brand in brands %}

<a href='{% url "store:home" %}?brand={{ brand.pk }}' 
class='navbar-item'>
    {{brand}}
</a>
{% endfor %}

top/store/templates/cart.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="section">
    <div class="columns ">
        <div class="column is-8">
            <div class="box">
                {% for item in cart_items %}
                <div class="modal {% if confirm_delete %} is-active {% endif %}">
                    <div class="modal-background"></div>
                    <div class="modal-content">
                        <div class="box has-text-centered">
                            <div class="title">
                                Подтвердите удаление
                            </div>
                            <a class="button is-success" href="{% url 'store:cart' %}?confirm=True&pk={{item.pk}}">
                                Подтвердить
                            </a>
                            <button class="button is-danger">Отмена</button>
                        </div>
                    </div>
                    <button class="modal-close is-large"></button>
                </div>
                <div class="columns">
                    <div class="column is-1">
                        {% if item.chosen %}
                        <a href="{% url 'store:cart' %}?action=remove_chosen&pk={{ item.pk }}">
                            <ion-icon name="checkbox-outline"></ion-icon>
                        </a>
                        {% else %}
                        <a href="{% url 'store:cart' %}?action=add_chosen&pk={{ item.pk }}">
                            <ion-icon name="square-outline"></ion-icon>
                        </a>
                        {% endif %}
                    </div>
                    <div class="column is-2">
                        <figure class="image is-128x128">
                            <img src="{{item.product.image.url}}">
                        </figure>
                    </div>
                    <div class="column is-4">
                        <div class="title is-3">{{ item.product.name }}</div>
                        <div class="subtitle is-7 has-text-grey">
                            {{item.product.category}}
                        </div>
                        <div class="buttons">
                            {% if user not in item.product.favorite.all %}
                            <a href="{% url 'store:cart' %}?action=favorite&product={{item.product.pk}}" class="button">
                                <ion-icon name="heart-outline"></ion-icon>
                            </a>
                            {% else %}
                            <a href="{% url 'store:cart' %}?action=favorite&product={{item.product.pk}}"
                                class="button is-link">
                                <ion-icon name="heart-outline"></ion-icon>
                            </a>
                            {% endif %}
                            <a href="{% url 'store:cart' %}?action=delete" class="button is-danger">Удалить</a>
                        </div>
                    </div>
                    <div class="column is-2">
                        {{item.total_price}} р
                    </div>
                    <div class="column">
                        <div class="field has-addons">
                            <div class="control">
                                <a href="{% url 'store:cart' %}?action=decrement&pk={{item.pk}}" class="button">
                                    <div class="title is-3">-</div>
                                </a>
                            </div>
                            <div class="control">
                                <button class="button">
                                    {{item.quantity}}
                                </button>
                            </div>
                            <div class="control">
                                <a class="button" href="{% url 'store:cart' %}?action=increment&pk={{item.pk}}">
                                    <div class="title is-3">+</div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <hr>
                {% endfor %}
            </div>
        </div>
        <div class="column">
            <div class="box">
                {% if chosen_items %}
                <a class="button is-success is-fullwidth" href="{% url 'store:create_order' %}">
                    Перейти к оформлению
                </a>
                {% endif %}
                <hr>
                <div class="block">
                    <div class="title is-5">Ваши товары</div>
                    <div class="subtitle is-6">
                        <span>Товары {{total_quantity}} шт</span>
                    </div>
                    <hr>
                    <div class="title is-5 is-flex is-justify-content-space-between">
                        <span>Общая сумма</span>
                        <span>{{total_sum}} р</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

top/store/templates/categories.html
<aside class="menu has-background-info-light p-3" style="min-height: 100%; border-radius: 10px;">
    <div class="menu-label">
        <div class="title">
            Категории
        </div>
    </div>
    <ul class="menu-list">
        {% for category in categories %}
        <li>
            <a href="{% url 'store:home' %}?category={{category.pk}}">
                {{category}}
            </a>
        </li>
        {% endfor %}
    </ul>
</aside>

top/store/templates/error.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="section">
    <div class="container">
        <div class="columns is-vcentered">
            <div class="column">
                <figure class="image is-256x256">
                    <img src="https://cdni.iconscout.com/illustration/premium/thumb/404-error-3702359-3119148.png"
                        alt="">
                </figure>
            </div>
            <div class="column">
                <div class="title is-2">
                    Что-то пошло не так
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

top/store/templates/favorite.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="section">
    <div class="container">
        <div class="columns is-multiline is-vcentered">
            {% for product in favorites %}
            <div class="column is-4">
                <div class="card">
                    <div class="card-image">
                        <a href="{% url 'store:product' product.pk %}">
                            <figure class="image">
                                <img src="{{ product.image.url }}" alt="">
                            </figure>
                        </a>
                        {% if product.is_new %}
                        <span class="tag is-danger">
                            Новинка!
                        </span>
                        {% endif %}

                        {% if product.is_discounted %}
                        <span class="tag is-primary">
                            Скидка!
                        </span>
                        {% endif %}
                    </div>
                    <div class="card-content">
                        <div class="media">
                            <br>
                            <div class="media-content">
                                <div class="title is-4">{{ product }}</div>
                            </div>
                        </div>
                        <div class="columns is-vcentered">
                            <div class="column">
                                <div class="content has-text-weight-bold">
                                    {{ product.price }} рублей
                                </div>
                            </div>
                            <div class="column has-text-right">
                                <a href="{% url 'store:guest_register' product.pk %}">
                                    <ion-icon name="cart-outline" class="order"></ion-icon>
                                </a>
                            </div>
                            <div class="column is-2">
                                {% if user not in product.favorite.all %}
                                <a href="{% url 'store:favorite' %}?action=favorite&product={{product.pk}}">
                                    <ion-icon name="heart-outline" class="order"></ion-icon>
                                </a>
                                {% else %}
                                <a href="{% url 'store:favorite' %}?action=favorite&product={{product.pk}}">
                                    <ion-icon name="heart" class="order has-text-danger"></ion-icon>
                                </a>
                                {% endif %}
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

top/store/templates/file_imnput.html
<div class="file">
    <label class="file_label">
        <input type="{{widget.type}}" class="file-input" name="{{widget.name}}"
        value="{{widget.velue|stringformat: 's' }}">
        <span class="file-cta">
            <ion-icon name="cloud-upload-outline" class="mr-2"></ion-icon>
            <span class="file-label">
                Выбрать файл...
            </span>
        </span>
    </label>
</div>

top/store/templates/home.html
{% extends 'base_layout.html' %}
{% load brand %}

{% block slider %}
<div class="container-slide">
    <div id="carousel-demo" class="carousel">
        {% for slide in slides %}
        <div class="item-1">
            <img class="slider-img" src="{{ slide.image.url }}" alt="">
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container" style="background-color: lightgreen; max-width: 100%; height: 100%;">
    <div class="columns mt-2">
        <div class="column is-one-fifth">
            {% brands %}
        </div>
        <div class="column">
            <div class="columns is-multiline is-centered">
                {% for product in products %}
                <div class="column is-4">
                    <div class="card">
                        <div class="card-image">
                            
                            <a href="{% url 'store:product' product.pk %}">
                                <figure class="image is-128x128">
                                    <img class="is-rounded" src="{{ product.image.url }}" alt="">
                                </figure>
                                {% if product.is_new or product.is_discounted %}
                                    <span class="tag is-danger">
                                        Новинка!
                                    </span>
                                    <span class="tag is-primary">
                                        Скидка!
                                    </span>
                                {% else %}
                                <br>
                                {% endif %}
                                </a>  
                        </div>
                        <div class="card-content">
                            <div class="media">
                                <div class="media-content">
                                    <div class="title is-4">{{ product }}</div>
                                </div>
                            </div>
                            <div class="columns is-vcentered">
                       
                                <div class="column">
                                    
                                    <div class="content has-text-weight-bold">
                                        {{ product.price }} рублей      
                                    </div>
                                </div>
                                <div class="column has-text-right">
                                    <a href="{% url 'store:guest_register' product.pk %}">
                                        <ion-icon name="cart-outline" class="order"></ion-icon>
                                    </a>
                                </div>
                                <div class="column is-2">
                                    {% if user not in product.favorite.all %}
                                    <a href="{% url 'store:home' %}?action=favorite&product={{product.pk}}" >
                                        <ion-icon name="heart-outline" class="order"></ion-icon>
                                    </a>
                                    {% else %}
                                    <a href="{% url 'store:home' %}?action=favorite&product={{product.pk}}"> 
                                        <ion-icon name="heart" class="order has-text-danger"></ion-icon>
                                    </a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
    
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% if products.has_other_pages %}
    <nav class="pagination is-centered has-text-danger">
        {% if products.has_previous %}
        <a class="pagination-previous has-text-white" href="?page={{ products.previous_page_number }}">Предыдущая страница</a>
        {% else %}
        <button class="pagination-previous has-text-white" disabled>Предыдущая страница</button>
        {% endif %}
        {% if products.has_next %}
        <a class="pagination-next has-text-white" href="?page={{ products.next_page_number }}">Следующая страница</a>
        {% else %}
        <button class="pagination-next has-text-white" disabled>Следующая страница</button>
        {% endif %}

        <ul class="pagination-list">
            {% for page in post_pages %}
            <li>
                <a class="pagination-link {% if page == products.number %} is-current {% endif %}" href="?page={{page}}">{{ page }}</a>
            </li>
            {% endfor %}
        </ul>
    </nav>
    {% endif %}
</div>
{% endblock %}